"use client";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Tabs from "@/components/tabs";
import NonSSRWrapper from "./NonSSRWrapper";
import QueryProvider from "./query-provider";
import useAppExit from "@/hooks/useAppExit";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useAppExit();

  return (
    <html lang="en">
      {/* <body className={inter.className}> */}
      <body>
        <NonSSRWrapper>
          <QueryProvider>
            <Providers>
              <Tabs>{children}</Tabs>
            </Providers>
          </QueryProvider>
        </NonSSRWrapper>
      </body>
    </html>
  );
}
